#exec-once = waybar
exec-once = ashell
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Auto lock screen after 5 minutes of inactivity
#exec-once = swayidle -w timeout 300 'hyprlock' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'

exec-once = $terminal

#exec-once = hyprshell run
#exec-once = $signal

exec-once = $discord
exec-once = $slack

exec-once = elephant
exec-once = walker --gapplication-service

# Notification Service
exec-once = swaync

# Initialize wallpaper symlink based on current theme before starting wpaperd
exec-once = ~/.config/hypr/scripts/theme-wallpaper init
exec-once = wpaperd -d

#exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"

## This will toggle HyprExpo when SUPER+g is pressed
#plugin {
#    hyprexpo {
#        columns = 3
#        gap_size = 5
#        bg_col = rgb(111111)
#        workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
#
#        gesture_distance = 300 # how far is the "max" for the gesture
#    }
#}
#bind = SUPER, g, hyprexpo:expo, toggle
