##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0



decoration:blur {
  brightness=0.5
  contrast=0.8
  enabled=true
  noise=0.09
  passes=4
  size=16
  vibrancy=0.8
  vibrancy_darkness=0.8
}

# Included in the Home Manager module
# layerrule = blur, ^(astal-)(.*)$
# layerrule = ignorezero, ^(astal-)(.*)$
# layerrule = animation popin, astal-launcher
# layerrule = animation slide right, astal-wallpapers
# layerrule = order 1, astal-powerMenu
